/*PROYECTOBD TIENE TODOS LOS PRIVILEGIOS*/
GRANT DBA TO PROYECTOBD;

/*CREAMOS EL USUARIO DE LAS PERSONAS*/
CREATE USER PERSONA IDENTIFIED BY PERSONA;

/*CREAMOS EL USUARIO DE LAS EMPRESAS*/
CREATE USER EMPRESA IDENTIFIED BY EMPRESA;

/*CREAMOS UN ROL PARA PERSONA*/
CREATE ROLE ROLPERSONA;

/*CREAMOS UN ROL PARA EMPRESA*/
CREATE ROLE ROLEMPRESA;

/*CONFIGURAMOS ROL DE UNA PERSONA*/
GRANT CREATE SESSION TO ROLPERSONA;
GRANT SELECT ON OFERTA TO ROLPERSONA;
GRANT SELECT, INSERT, UPDATE, DELETE ON CURRICULUM TO ROLPERSONA;
GRANT SELECT, INSERT, DELETE ON SE_INSCRIBEN TO ROLPERSONA;
GRANT SELECT, UPDATE ON USUARIO TO ROLPERSONA;
GRANT SELECT, UPDATE ON PERSONA TO ROLPERSONA;
GRANT SELECT ON EMPRESA TO ROLPERSONA;

/*CONFIGURAMOS ROL DE UNA PERSONA*/
GRANT CREATE SESSION TO ROLEMPRESA;
GRANT SELECT, INSERT, UPDATE, DELETE ON OFERTA TO ROLEMPRESA;
GRANT SELECT ON CURRICULUM TO ROLEMPRESA;
GRANT SELECT ON SE_INSCRIBEN TO ROLEMPRESA;
GRANT SELECT, UPDATE ON USUARIO TO ROLEMPRESA;
GRANT SELECT ON PERSONA TO ROLEMPRESA;
GRANT SELECT, UPDATE ON EMPRESA TO ROLEMPRESA;

/*ASIGNAMOS EL ROL A PERSONA*/
GRANT ROLPERSONA TO PERSONA;

/*ASIGNAMOS EL ROL A EMPRESA*/
GRANT ROLEMPRESA TO EMPRESA;
