package Vista;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * @author domprien
 */
public class CrearCurriculum extends javax.swing.JFrame {

    private VentanaPrincipal padre;
    
    /**
     * Creates new form Ofensas
     * @param vtn
     */
    public CrearCurriculum(VentanaPrincipal vtn) {
        initComponents();
        padre = vtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        experienciaE = new javax.swing.JLabel();
        experiencia = new javax.swing.JTextField();
        formacionE = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formacion = new javax.swing.JTextArea();
        idiomasE = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        idiomas = new javax.swing.JTextArea();
        enviarCurriculum = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        gustos = new javax.swing.JTextArea();
        gustosE = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        otros = new javax.swing.JTextArea();
        otrosE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir curriculum");
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(610, 499));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(610, 499));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(610, 499));

        experienciaE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        experienciaE.setText("Experiencia");

        experiencia.setMaximumSize(new java.awt.Dimension(84, 29));
        experiencia.setMinimumSize(new java.awt.Dimension(84, 29));
        experiencia.setPreferredSize(new java.awt.Dimension(84, 29));

        formacionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formacionE.setText("Formacion");

        formacion.setColumns(20);
        formacion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        formacion.setLineWrap(true);
        formacion.setRows(5);
        jScrollPane2.setViewportView(formacion);

        idiomasE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idiomasE.setText("Idiomas");

        idiomas.setColumns(20);
        idiomas.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        idiomas.setLineWrap(true);
        idiomas.setRows(5);
        jScrollPane3.setViewportView(idiomas);

        enviarCurriculum.setText("Enviar");
        enviarCurriculum.setMaximumSize(new java.awt.Dimension(125, 40));
        enviarCurriculum.setMinimumSize(new java.awt.Dimension(125, 40));
        enviarCurriculum.setPreferredSize(new java.awt.Dimension(125, 40));

        gustos.setColumns(20);
        gustos.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        gustos.setLineWrap(true);
        gustos.setRows(5);
        jScrollPane4.setViewportView(gustos);

        gustosE.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        gustosE.setText("Gustos y aficiones");

        otros.setColumns(20);
        otros.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        otros.setLineWrap(true);
        otros.setRows(5);
        jScrollPane5.setViewportView(otros);

        otrosE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        otrosE.setText("Otros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enviarCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(experienciaE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(formacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(idiomasE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gustosE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(otrosE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experienciaE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idiomasE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gustosE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otrosE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(enviarCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Getter y Setter">
    public JTextField getExperiencia() {
        return experiencia;
    }

    public void setExperiencia(JTextField experiencia) {
        this.experiencia = experiencia;
    }

    public JTextArea getFormacion() {
        return formacion;
    }

    public void setFormacion(JTextArea formacion) {
        this.formacion = formacion;
    }

    public JTextArea getGustos() {
        return gustos;
    }

    public void setGustos(JTextArea gustos) {
        this.gustos = gustos;
    }

    public JTextArea getIdiomas() {
        return idiomas;
    }

    public void setIdiomas(JTextArea idiomas) {
        this.idiomas = idiomas;
    }

    public JTextArea getOtros() {
        return otros;
    }

    public void setOtros(JTextArea otros) {
        this.otros = otros;
    }

    public VentanaPrincipal getPadre()
    {
        return padre;
    }
    
    public JButton getEnviarCurriculum()
    {
        return enviarCurriculum;
    }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarCurriculum;
    private javax.swing.JTextField experiencia;
    private javax.swing.JLabel experienciaE;
    private javax.swing.JTextArea formacion;
    private javax.swing.JLabel formacionE;
    private javax.swing.JTextArea gustos;
    private javax.swing.JLabel gustosE;
    private javax.swing.JTextArea idiomas;
    private javax.swing.JLabel idiomasE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea otros;
    private javax.swing.JLabel otrosE;
    // End of variables declaration//GEN-END:variables
}
