package Vista;

import Modelo.Textos;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * @author Enrique Dominguez Prieto
 */
public class CrearUsuario extends javax.swing.JFrame {

    private VentanaPrincipal padre;
    private String direccionImagenPerfil = "";
    
    /**
     * Creates new form QueRicoCulo
     */
    public CrearUsuario(VentanaPrincipal vtn) {
        initComponents();
	padre = vtn;
	setLocationRelativeTo(padre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tipoUsuario = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        userE = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        informacionE = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTextArea();
        contactoE = new javax.swing.JLabel();
        coinciden = new javax.swing.JLabel();
        crearCuenta = new javax.swing.JButton();
        iniciarSesion = new javax.swing.JLabel();
        tipoEmpresa = new javax.swing.JRadioButton();
        tipoPersona = new javax.swing.JRadioButton();
        profileImage = new javax.swing.JLabel();
        seleccionarImagen = new javax.swing.JButton();
        nombreE = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        passE = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        repeatPassE = new javax.swing.JLabel();
        repeatPass = new javax.swing.JPasswordField();
        direccionE = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        ciudadE = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        telefonoE = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        mailE = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        DNIE = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        apellido1E = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        apellido2E = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        fechaNacimientoE = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JTextField();
        nacionalidadE = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JTextField();
        conducirE = new javax.swing.JLabel();
        conducir = new javax.swing.JRadioButton();
        CIFE = new javax.swing.JLabel();
        CIF = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        contacto = new javax.swing.JTextArea();
        URLE = new javax.swing.JLabel();
        URL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear usuario");
        setPreferredSize(new java.awt.Dimension(610, 499));
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(605, 405));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(605, 405));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(605, 405));

        jPanel1.setPreferredSize(new java.awt.Dimension(610, 600));

        userE.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        userE.setText("Nombre de usuario");

        user.setMaximumSize(new java.awt.Dimension(84, 29));
        user.setMinimumSize(new java.awt.Dimension(84, 29));
        user.setPreferredSize(new java.awt.Dimension(84, 29));

        informacionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        informacionE.setText("Informacion");

        informacion.setColumns(20);
        informacion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        informacion.setLineWrap(true);
        informacion.setRows(5);
        jScrollPane3.setViewportView(informacion);

        contactoE.setText("Persona de contacto");

        coinciden.setMaximumSize(new java.awt.Dimension(78, 20));
        coinciden.setMinimumSize(new java.awt.Dimension(78, 20));
        coinciden.setPreferredSize(new java.awt.Dimension(78, 20));

        crearCuenta.setText("Crear Cuenta");
        crearCuenta.setMaximumSize(new java.awt.Dimension(125, 40));
        crearCuenta.setMinimumSize(new java.awt.Dimension(125, 40));
        crearCuenta.setPreferredSize(new java.awt.Dimension(125, 40));

        iniciarSesion.setText("<html>¿Tienes ya una cuenta? <b>Inicia sesión</b></html>");
        iniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tipoEmpresa.setText(Textos.ENTERPRISETYPE);

        tipoPersona.setText(Textos.USERTYPE);

        profileImage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        profileImage.setText("Imagen de perfil");

        seleccionarImagen.setText("Seleccionar Imagen de perfil");

        nombreE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreE.setText("Nombre");

        nombre.setMaximumSize(new java.awt.Dimension(84, 29));
        nombre.setMinimumSize(new java.awt.Dimension(84, 29));
        nombre.setPreferredSize(new java.awt.Dimension(84, 29));

        passE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passE.setText("Contraseña");

        repeatPassE.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        repeatPassE.setText("Repetir contraseña");

        direccionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        direccionE.setText("Direccion");

        direccion.setMaximumSize(new java.awt.Dimension(84, 29));
        direccion.setMinimumSize(new java.awt.Dimension(84, 29));
        direccion.setPreferredSize(new java.awt.Dimension(84, 29));

        ciudadE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ciudadE.setText("Ciudad");

        ciudad.setMaximumSize(new java.awt.Dimension(84, 29));
        ciudad.setMinimumSize(new java.awt.Dimension(84, 29));
        ciudad.setPreferredSize(new java.awt.Dimension(84, 29));

        telefonoE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        telefonoE.setText("Teléfono");

        telefono.setMaximumSize(new java.awt.Dimension(84, 29));
        telefono.setMinimumSize(new java.awt.Dimension(84, 29));
        telefono.setPreferredSize(new java.awt.Dimension(84, 29));

        mailE.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        mailE.setText("Correo electronico");

        mail.setMaximumSize(new java.awt.Dimension(84, 29));
        mail.setMinimumSize(new java.awt.Dimension(84, 29));
        mail.setPreferredSize(new java.awt.Dimension(84, 29));

        DNIE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DNIE.setText("DNI");

        DNI.setMaximumSize(new java.awt.Dimension(84, 29));
        DNI.setMinimumSize(new java.awt.Dimension(84, 29));
        DNI.setPreferredSize(new java.awt.Dimension(84, 29));

        apellido1E.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apellido1E.setText("Primer apellido");

        apellido1.setMaximumSize(new java.awt.Dimension(84, 29));
        apellido1.setMinimumSize(new java.awt.Dimension(84, 29));
        apellido1.setPreferredSize(new java.awt.Dimension(84, 29));

        apellido2E.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        apellido2E.setText("Segundo apellido");

        apellido2.setMaximumSize(new java.awt.Dimension(84, 29));
        apellido2.setMinimumSize(new java.awt.Dimension(84, 29));
        apellido2.setPreferredSize(new java.awt.Dimension(84, 29));

        fechaNacimientoE.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        fechaNacimientoE.setText("Fecha nacimiento");

        fechaNacimiento.setMaximumSize(new java.awt.Dimension(84, 29));
        fechaNacimiento.setMinimumSize(new java.awt.Dimension(84, 29));
        fechaNacimiento.setPreferredSize(new java.awt.Dimension(84, 29));

        nacionalidadE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nacionalidadE.setText("Nacionalidad");

        nacionalidad.setMaximumSize(new java.awt.Dimension(84, 29));
        nacionalidad.setMinimumSize(new java.awt.Dimension(84, 29));
        nacionalidad.setPreferredSize(new java.awt.Dimension(84, 29));

        conducirE.setText("Permiso de conducir");

        CIFE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CIFE.setText("CIF");

        CIF.setMaximumSize(new java.awt.Dimension(84, 29));
        CIF.setMinimumSize(new java.awt.Dimension(84, 29));
        CIF.setPreferredSize(new java.awt.Dimension(84, 29));

        contacto.setColumns(20);
        contacto.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        contacto.setLineWrap(true);
        contacto.setRows(5);
        jScrollPane4.setViewportView(contacto);

        URLE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        URLE.setText("URL");

        URL.setMaximumSize(new java.awt.Dimension(84, 29));
        URL.setMinimumSize(new java.awt.Dimension(84, 29));
        URL.setPreferredSize(new java.awt.Dimension(84, 29));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(profileImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seleccionarImagen))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(userE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(passE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(repeatPassE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(repeatPass, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ciudadE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(telefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(mailE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(coinciden, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(informacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(CIFE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CIF, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(conducirE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(conducir))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nacionalidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(DNIE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(apellido2E, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(apellido1E, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fechaNacimientoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(contactoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(URLE, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(URL, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(tipoPersona)
                .addGap(41, 41, 41)
                .addComponent(tipoEmpresa)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(repeatPassE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(repeatPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coinciden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ciudadE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileImage)
                    .addComponent(seleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoEmpresa)
                    .addComponent(tipoPersona))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DNIE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido1E, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido2E, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaNacimientoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacionalidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conducir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conducirE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CIFE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(URLE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Getter y Setter">
    public JTextField getApellido1() {
        return apellido1;
    }

    public void setApellido1(JTextField apellido1) {
        this.apellido1 = apellido1;
    }

    public JTextField getApellido2() {
        return apellido2;
    }

    public void setApellido2(JTextField apellido2) {
        this.apellido2 = apellido2;
    }

    public JTextField getCIF() {
        return CIF;
    }

    public void setCIF(JTextField cif) {
        this.CIF = cif;
    }

    public JTextField getCiudad() {
        return ciudad;
    }

    public void setCiudad(JTextField ciudad) {
        this.ciudad = ciudad;
    }

    public JRadioButton getConducir() {
        return conducir;
    }

    public void setConducir(JRadioButton conducir) {
        this.conducir = conducir;
    }

    public JTextArea getContacto() {
        return contacto;
    }

    public void setContacto(JTextArea contacto) {
        this.contacto = contacto;
    }

    public JPasswordField getPass() {
        return pass;
    }

    public void setPass(JPasswordField contraseña) {
        this.pass = contraseña;
    }

    public JTextField getMail() {
        return mail;
    }

    public void setMail(JTextField correo) {
        this.mail = correo;
    }

    public JTextField getDireccion() {
        return direccion;
    }

    public void setDireccion(JTextField direccion) {
        this.direccion = direccion;
    }

    public JTextField getDNI() {
        return DNI;
    }

    public void setDNI(JTextField dni) {
        this.DNI = dni;
    }

    public JTextField getFechaNacimiento() {
        return fechaNacimiento;
    }

    public void setFechaNacimiento(JTextField fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public JTextArea getInformacion() {
        return informacion;
    }

    public void setInformacion(JTextArea informacion) {
        this.informacion = informacion;
    }

    public JTextField getNacionalidad() {
        return nacionalidad;
    }

    public void setNacionalidad(JTextField nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    public JTextField getUser() {
        return user;
    }

    public void setUser(JTextField nombreUsuario) {
        this.user = nombreUsuario;
    }

    public JPasswordField getRepeatPass() {
        return repeatPass;
    }

    public void setRepeatPass(JPasswordField repContraseña) {
        this.repeatPass = repContraseña;
    }

    public JTextField getTelefono() {
        return telefono;
    }

    public void setTelefono(JTextField telefono) {
        this.telefono = telefono;
    }

    public VentanaPrincipal getPadre()
    {
        return padre;
    }
    
    public JButton getCrearCuenta()
    {
        return crearCuenta;
    }

    public JLabel getCoinciden()
    {
        return coinciden;
    }

    public void setCoinciden(JLabel coinciden)
    {
        this.coinciden = coinciden;
    }

    public JButton getSeleccionarImagen()
    {
        return seleccionarImagen;
    }

    public String getDireccionImagenPerfil()
    {
        return direccionImagenPerfil;
    }

    public void setDireccionImagenPerfil(String direccionImagenPerfil)
    {
        this.direccionImagenPerfil = direccionImagenPerfil;
    }

    public JLabel getIniciarSesion()
    {
        return iniciarSesion;
    }

    public ButtonGroup getTipoUsuario()
    {
        return tipoUsuario;
    }

    public JRadioButton getTipoEmpresa()
    {
        return tipoEmpresa;
    }

    public JRadioButton getTipoPersona()
    {
        return tipoPersona;
    }

    public JLabel getCIFE()
    {
        return CIFE;
    }

    public JLabel getDNIE()
    {
        return DNIE;
    }

    public JLabel getApellido1E()
    {
        return apellido1E;
    }

    public JLabel getApellido2E()
    {
        return apellido2E;
    }

    public JLabel getConducirE()
    {
        return conducirE;
    }

    public JLabel getContactoE()
    {
        return contactoE;
    }

    public JLabel getFechaNacimientoE()
    {
        return fechaNacimientoE;
    }

    public JLabel getInformacionE()
    {
        return informacionE;
    }

    public JLabel getNacionalidadE()
    {
        return nacionalidadE;
    }

    public JScrollPane getjScrollPane3()
    {
        return jScrollPane3;
    }

    public JScrollPane getjScrollPane4()
    {
        return jScrollPane4;
    }
    
    public JPanel getJPanel1()
    {
        return jPanel1;
    }
    
    public JTextField getURL()
    {
        return URL;
    }

    public JLabel getURLE()
    {
        return URLE;
    }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CIF;
    private javax.swing.JLabel CIFE;
    private javax.swing.JTextField DNI;
    private javax.swing.JLabel DNIE;
    private javax.swing.JTextField URL;
    private javax.swing.JLabel URLE;
    private javax.swing.JTextField apellido1;
    private javax.swing.JLabel apellido1E;
    private javax.swing.JTextField apellido2;
    private javax.swing.JLabel apellido2E;
    private javax.swing.JTextField ciudad;
    private javax.swing.JLabel ciudadE;
    private javax.swing.JLabel coinciden;
    private javax.swing.JRadioButton conducir;
    private javax.swing.JLabel conducirE;
    private javax.swing.JTextArea contacto;
    private javax.swing.JLabel contactoE;
    private javax.swing.JButton crearCuenta;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionE;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JLabel fechaNacimientoE;
    private javax.swing.JTextArea informacion;
    private javax.swing.JLabel informacionE;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel mailE;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JLabel nacionalidadE;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreE;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passE;
    private javax.swing.JLabel profileImage;
    private javax.swing.JPasswordField repeatPass;
    private javax.swing.JLabel repeatPassE;
    private javax.swing.JButton seleccionarImagen;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoE;
    private javax.swing.JRadioButton tipoEmpresa;
    private javax.swing.JRadioButton tipoPersona;
    private javax.swing.ButtonGroup tipoUsuario;
    private javax.swing.JTextField user;
    private javax.swing.JLabel userE;
    // End of variables declaration//GEN-END:variables
}
