package Vista;

import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * @author Enrique Dominguez Prieto
 */
public class Ofertas extends javax.swing.JFrame 
{

    private VentanaPrincipal padre;
    
    /**
     * Creates new form QueRicoCulo
     * @param vtn
     */
    public Ofertas(VentanaPrincipal vtn) 
    {
        initComponents();
        padre = vtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        puestoE = new javax.swing.JLabel();
        puesto = new javax.swing.JTextField();
        descripcionE = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        vacantes = new javax.swing.JSpinner();
        vacantesE = new javax.swing.JLabel();
        ubicacionE = new javax.swing.JLabel();
        ubicacion = new javax.swing.JTextField();
        requisitosE = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        requisitos = new javax.swing.JTextArea();
        salarioE = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        jornadaE = new javax.swing.JLabel();
        jornada = new javax.swing.JTextField();
        vacacionesE = new javax.swing.JLabel();
        vacaciones = new javax.swing.JTextField();
        crearOferta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear oferta");
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(610, 499));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(610, 499));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(610, 499));

        puestoE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        puestoE.setText("Puesto");

        puesto.setMaximumSize(new java.awt.Dimension(84, 29));
        puesto.setMinimumSize(new java.awt.Dimension(84, 29));
        puesto.setPreferredSize(new java.awt.Dimension(84, 29));

        descripcionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        descripcionE.setText("Descripcion");

        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        jScrollPane2.setViewportView(descripcion);

        vacantes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        vacantesE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vacantesE.setText("Vacantes");

        ubicacionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ubicacionE.setText("Ubicacion");

        ubicacion.setMaximumSize(new java.awt.Dimension(84, 29));
        ubicacion.setMinimumSize(new java.awt.Dimension(84, 29));
        ubicacion.setPreferredSize(new java.awt.Dimension(84, 29));

        requisitosE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        requisitosE.setText("Requisitos");

        requisitos.setColumns(20);
        requisitos.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        requisitos.setLineWrap(true);
        requisitos.setRows(5);
        jScrollPane3.setViewportView(requisitos);

        salarioE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salarioE.setText("Salario");

        salario.setMaximumSize(new java.awt.Dimension(84, 29));
        salario.setMinimumSize(new java.awt.Dimension(84, 29));
        salario.setPreferredSize(new java.awt.Dimension(84, 29));

        jornadaE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jornadaE.setText("Jornada");

        jornada.setMaximumSize(new java.awt.Dimension(84, 29));
        jornada.setMinimumSize(new java.awt.Dimension(84, 29));
        jornada.setPreferredSize(new java.awt.Dimension(84, 29));

        vacacionesE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vacacionesE.setText("Vacaciones");

        vacaciones.setMaximumSize(new java.awt.Dimension(84, 29));
        vacaciones.setMinimumSize(new java.awt.Dimension(84, 29));
        vacaciones.setPreferredSize(new java.awt.Dimension(84, 29));

        crearOferta.setText("Siguiente");
        crearOferta.setMaximumSize(new java.awt.Dimension(125, 40));
        crearOferta.setMinimumSize(new java.awt.Dimension(125, 40));
        crearOferta.setPreferredSize(new java.awt.Dimension(125, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crearOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(vacacionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(vacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jornadaE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jornada, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(salarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(puestoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(descripcionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vacantesE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ubicacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(vacantes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(requisitosE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane3))))))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puestoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vacantes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacantesE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubicacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requisitosE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jornadaE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vacacionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(crearOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Getter y Setter">
    public JTextArea getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(JTextArea descripcion) {
        this.descripcion = descripcion;
    }

    public JTextField getJornada() {
        return jornada;
    }

    public void setJornada(JTextField jornada) {
        this.jornada = jornada;
    }

    public JTextField getPuesto() {
        return puesto;
    }

    public void setPuesto(JTextField puesto) {
        this.puesto = puesto;
    }

    public JTextArea getRequisitos() {
        return requisitos;
    }

    public void setRequisitos(JTextArea requisitos) {
        this.requisitos = requisitos;
    }

    public JTextField getSalario() {
        return salario;
    }

    public void setSalario(JTextField salario) {
        this.salario = salario;
    }

    public JTextField getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(JTextField ubicacion) {
        this.ubicacion = ubicacion;
    }

    public JTextField getVacaciones() {
        return vacaciones;
    }

    public void setVacaciones(JTextField vacaciones) {
        this.vacaciones = vacaciones;
    }

    public JSpinner getVacantes() {
        return vacantes;
    }

    public void setVacantes(JSpinner vacantes) {
        this.vacantes = vacantes;
    }

    public VentanaPrincipal getPadre()
    {
        return padre;
    }

    public void setPadre(VentanaPrincipal padre)
    {
        this.padre = padre;
    }

    public JButton getCrearOferta()
    {
        return crearOferta;
    }
    //</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearOferta;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel descripcionE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jornada;
    private javax.swing.JLabel jornadaE;
    private javax.swing.JTextField puesto;
    private javax.swing.JLabel puestoE;
    private javax.swing.JTextArea requisitos;
    private javax.swing.JLabel requisitosE;
    private javax.swing.JTextField salario;
    private javax.swing.JLabel salarioE;
    private javax.swing.JTextField ubicacion;
    private javax.swing.JLabel ubicacionE;
    private javax.swing.JTextField vacaciones;
    private javax.swing.JLabel vacacionesE;
    private javax.swing.JSpinner vacantes;
    private javax.swing.JLabel vacantesE;
    // End of variables declaration//GEN-END:variables
}
