/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Entidades.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author pabli
 */
public class VentanaPrincipal extends javax.swing.JFrame 
{
    /**
     * Usuario que inciia sesión en la aplicación.
     */
    private Usuario usuario;
    /**
     * Referencia a la ventana de inicio de sesión de la aplicación.
     */
    private Loging inicioSesion;
    /**
     * Referencia a la ventana de Crear Usuario de la aplicación.
     */
    private CrearUsuario registrar;
    /**
     * Referencia a la vetnana de Configuración de la aplicación.
     */
    private Configuracion configuracion;
    /**
     * Referencia a la ventana de Crear Curriculum de la aplicación.
     */
    private CrearCurriculum curriculum;
    /**
     * Referencia a la ventanan de Crear Oferta de la aplicación.
     */
    private Ofertas oferta;
    /**
     * Lista de Objetos a mostrar en el Panel Invisible del Panel Principal.
     */
    private ArrayList<Object> resultados = new ArrayList<>();
    /**
     * Color por defecto de la aplicación en general.
     */
    private static Color colorDefecto;
    /**
     * Color por defecto del texto de la aplicación en general.
     */
    private static Color colorTextoDefecto;
    /**
     * Color por defecto de las cajas de texto de la aplicación en general.
     */
    private static Color colorJTextFieldDefecto;
    /**
     *  Color por defecto del texto de las cajas de texto.
     */
    private static Color colorJTextFieldTextoDefecto;
    /**
     * Variable que indica si los botones de Iniciar Sesión y Registrarse deben estar visibles.
     */
    private boolean botonActivado = true;
    /**
     * Variable que indica si se ha iniciado sesión o no.
     */
    private boolean textoActivado = false;
    /**
     * Variable que indica si se está mostrando un curriculum o no.
     */
    private boolean mostrarCurriculum = false;
    /**
     * Lista de Componentes que muestra la aplicación en la vista de Usuario.
     */
    private ArrayList<Component> arr = new ArrayList<>();
    /**
     * Variable que indica que se ha abierto el menú desplegable.
     */
    private boolean menuAbierto;
    
    /** Creates new form Main */
    public VentanaPrincipal() 
    {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Metal".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) 
        {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        barraSuperior = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        busqueda = new javax.swing.JTextField();
        busquedaI = new javax.swing.JLabel();
        etiquetaVacia = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JButton();
        registrarse = new javax.swing.JButton();
        usuarioI = new javax.swing.JLabel();
        hamburguerMenu = new javax.swing.JPanel();
        opciones = new javax.swing.JList<>();
        ventanaPrincipal = new javax.swing.JPanel();
        ofertasScroll = new javax.swing.JScrollPane();
        panelInvisible = new javax.swing.JPanel();
        panelCurriculum = new javax.swing.JPanel();
        editar = new javax.swing.JButton();
        actualizacion = new javax.swing.JTextField();
        actualizacionE = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        correoE = new javax.swing.JLabel();
        nombreCurriculum = new javax.swing.JTextField();
        nombreCurriculumE = new javax.swing.JLabel();
        apellido1CurriculumE = new javax.swing.JLabel();
        apellido1Curriculum = new javax.swing.JTextField();
        apellido2CurriculumE = new javax.swing.JLabel();
        apellido2Curriculum = new javax.swing.JTextField();
        formacionE = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        formacion = new javax.swing.JTextArea();
        experienciaE = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        experiencia = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        aficiones = new javax.swing.JTextArea();
        aficionesE = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        idiomas = new javax.swing.JTextArea();
        idiomasE = new javax.swing.JLabel();
        otrosE = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        otros = new javax.swing.JTextArea();
        aceptarCambiosCurriculum = new javax.swing.JButton();
        borrarCurriculum = new javax.swing.JButton();
        panelOferta = new javax.swing.JPanel();
        editarOferta = new javax.swing.JButton();
        nombreEmpresa = new javax.swing.JTextField();
        nombreEmpresaE = new javax.swing.JLabel();
        puestoE = new javax.swing.JLabel();
        puesto = new javax.swing.JTextField();
        ubicacionE = new javax.swing.JLabel();
        ubicacion = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        requisitos = new javax.swing.JTextArea();
        requisitosE = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        descripcionE = new javax.swing.JLabel();
        salarioE = new javax.swing.JLabel();
        inscritosE = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        inscritos = new javax.swing.JTextField();
        jornadaE = new javax.swing.JLabel();
        vacacionesE = new javax.swing.JLabel();
        jornada = new javax.swing.JTextField();
        vacaciones = new javax.swing.JTextField();
        vacantesE = new javax.swing.JLabel();
        creacionE = new javax.swing.JLabel();
        vacantes = new javax.swing.JTextField();
        creacion = new javax.swing.JTextField();
        aceptarCambiosOferta = new javax.swing.JButton();
        borrarOferta = new javax.swing.JButton();
        panelUsuario = new javax.swing.JPanel();
        editarUsuario = new javax.swing.JButton();
        nombreUser = new javax.swing.JTextField();
        nombreUserE = new javax.swing.JLabel();
        usuarioI1 = new javax.swing.JLabel();
        apellido1UsuarioE = new javax.swing.JLabel();
        apellido1Usuario = new javax.swing.JTextField();
        apellido2UsuarioE = new javax.swing.JLabel();
        apellido2Usuario = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        telefonoE = new javax.swing.JLabel();
        correo1 = new javax.swing.JTextField();
        correoE1 = new javax.swing.JLabel();
        direccionE = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        ciudadE = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        nacionalidad = new javax.swing.JTextField();
        nacionalidadE = new javax.swing.JLabel();
        nacimiento = new javax.swing.JTextField();
        nacimientoE = new javax.swing.JLabel();
        conducir = new javax.swing.JCheckBox();
        jScrollPane10 = new javax.swing.JScrollPane();
        contacto = new javax.swing.JTextArea();
        contactoE = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTextArea();
        informacionE = new javax.swing.JLabel();
        urlE = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        aceptarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portal de empleo");
        setMinimumSize(new java.awt.Dimension(1195, 610));
        setResizable(false);

        barraSuperior.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        barraSuperior.setMinimumSize(new java.awt.Dimension(1170, 62));
        barraSuperior.setPreferredSize(new java.awt.Dimension(1170, 62));

        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setMaximumSize(new java.awt.Dimension(59, 40));
        menu.setMinimumSize(new java.awt.Dimension(59, 40));
        menu.setPreferredSize(new java.awt.Dimension(59, 40));
        barraSuperior.add(menu);

        busqueda.setMinimumSize(new java.awt.Dimension(660, 40));
        busqueda.setPreferredSize(new java.awt.Dimension(660, 40));
        barraSuperior.add(busqueda);

        busquedaI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busquedaI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busquedaI.setMaximumSize(new java.awt.Dimension(45, 40));
        busquedaI.setMinimumSize(new java.awt.Dimension(45, 40));
        busquedaI.setPreferredSize(new java.awt.Dimension(45, 40));
        barraSuperior.add(busquedaI);

        etiquetaVacia.setMaximumSize(new java.awt.Dimension(50, 40));
        etiquetaVacia.setMinimumSize(new java.awt.Dimension(50, 40));
        etiquetaVacia.setName(""); // NOI18N
        etiquetaVacia.setPreferredSize(new java.awt.Dimension(50, 40));
        barraSuperior.add(etiquetaVacia);

        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreUsuario.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        nombreUsuario.setMinimumSize(new java.awt.Dimension(283, 40));
        nombreUsuario.setPreferredSize(new java.awt.Dimension(283, 40));
        barraSuperior.add(nombreUsuario);

        iniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setText("Iniciar sesión");
        iniciarSesion.setBorder(null);
        iniciarSesion.setContentAreaFilled(false);
        iniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        iniciarSesion.setMaximumSize(new java.awt.Dimension(125, 40));
        iniciarSesion.setMinimumSize(new java.awt.Dimension(125, 40));
        iniciarSesion.setPreferredSize(new java.awt.Dimension(125, 40));
        barraSuperior.add(iniciarSesion);

        registrarse.setText("Registrarse");
        registrarse.setBorder(null);
        registrarse.setContentAreaFilled(false);
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarse.setMaximumSize(new java.awt.Dimension(125, 40));
        registrarse.setMinimumSize(new java.awt.Dimension(125, 40));
        registrarse.setPreferredSize(new java.awt.Dimension(125, 40));
        barraSuperior.add(registrarse);

        usuarioI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioI.setMaximumSize(new java.awt.Dimension(59, 48));
        usuarioI.setMinimumSize(new java.awt.Dimension(59, 48));
        usuarioI.setPreferredSize(new java.awt.Dimension(59, 48));
        barraSuperior.add(usuarioI);

        opciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout hamburguerMenuLayout = new javax.swing.GroupLayout(hamburguerMenu);
        hamburguerMenu.setLayout(hamburguerMenuLayout);
        hamburguerMenuLayout.setHorizontalGroup(
            hamburguerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hamburguerMenuLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        hamburguerMenuLayout.setVerticalGroup(
            hamburguerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hamburguerMenuLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        ventanaPrincipal.setMaximumSize(new java.awt.Dimension(1195, 520));
        ventanaPrincipal.setMinimumSize(new java.awt.Dimension(939, 520));
        ventanaPrincipal.setPreferredSize(new java.awt.Dimension(939, 520));

        ofertasScroll.setBorder(null);
        ofertasScroll.setToolTipText("");
        ofertasScroll.setMaximumSize(new java.awt.Dimension(1195, 520));
        ofertasScroll.setName(""); // NOI18N
        ofertasScroll.setRequestFocusEnabled(false);

        panelInvisible.setMaximumSize(new java.awt.Dimension(1195, 1000));
        panelInvisible.setPreferredSize(new java.awt.Dimension(940, 520));

        javax.swing.GroupLayout panelInvisibleLayout = new javax.swing.GroupLayout(panelInvisible);
        panelInvisible.setLayout(panelInvisibleLayout);
        panelInvisibleLayout.setHorizontalGroup(
            panelInvisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
        );
        panelInvisibleLayout.setVerticalGroup(
            panelInvisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        ofertasScroll.setViewportView(panelInvisible);

        panelCurriculum.setPreferredSize(new java.awt.Dimension(940, 520));

        editar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editar.setText("Editar");

        actualizacion.setMaximumSize(new java.awt.Dimension(84, 29));
        actualizacion.setMinimumSize(new java.awt.Dimension(84, 29));
        actualizacion.setPreferredSize(new java.awt.Dimension(84, 29));

        actualizacionE.setText("Ultima actualizacion");

        correo.setMaximumSize(new java.awt.Dimension(84, 29));
        correo.setMinimumSize(new java.awt.Dimension(84, 29));
        correo.setPreferredSize(new java.awt.Dimension(84, 29));

        correoE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        correoE.setText("Correo");

        nombreCurriculum.setMaximumSize(new java.awt.Dimension(84, 29));
        nombreCurriculum.setMinimumSize(new java.awt.Dimension(84, 29));
        nombreCurriculum.setPreferredSize(new java.awt.Dimension(84, 29));

        nombreCurriculumE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreCurriculumE.setText("Nombre");

        apellido1CurriculumE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apellido1CurriculumE.setText("Primer apellido");

        apellido1Curriculum.setMaximumSize(new java.awt.Dimension(84, 29));
        apellido1Curriculum.setMinimumSize(new java.awt.Dimension(84, 29));
        apellido1Curriculum.setPreferredSize(new java.awt.Dimension(84, 29));

        apellido2CurriculumE.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        apellido2CurriculumE.setText("Segundo apellido");

        apellido2Curriculum.setMaximumSize(new java.awt.Dimension(84, 29));
        apellido2Curriculum.setMinimumSize(new java.awt.Dimension(84, 29));
        apellido2Curriculum.setPreferredSize(new java.awt.Dimension(84, 29));

        formacionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formacionE.setText("Formacion");

        formacion.setColumns(20);
        formacion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        formacion.setLineWrap(true);
        formacion.setRows(5);
        jScrollPane3.setViewportView(formacion);

        experienciaE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        experienciaE.setText("Experiencia");

        experiencia.setColumns(20);
        experiencia.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        experiencia.setLineWrap(true);
        experiencia.setRows(5);
        jScrollPane4.setViewportView(experiencia);

        aficiones.setColumns(20);
        aficiones.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        aficiones.setLineWrap(true);
        aficiones.setRows(5);
        jScrollPane6.setViewportView(aficiones);

        aficionesE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aficionesE.setText("Aficiones");

        idiomas.setColumns(20);
        idiomas.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        idiomas.setLineWrap(true);
        idiomas.setRows(5);
        jScrollPane5.setViewportView(idiomas);

        idiomasE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idiomasE.setText("Idiomas");

        otrosE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        otrosE.setText("Otros");

        otros.setColumns(20);
        otros.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        otros.setLineWrap(true);
        otros.setRows(5);
        jScrollPane8.setViewportView(otros);

        aceptarCambiosCurriculum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aceptarCambiosCurriculum.setText("Aceptar");

        borrarCurriculum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        borrarCurriculum.setText("Borrar");

        javax.swing.GroupLayout panelCurriculumLayout = new javax.swing.GroupLayout(panelCurriculum);
        panelCurriculum.setLayout(panelCurriculumLayout);
        panelCurriculumLayout.setHorizontalGroup(
            panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurriculumLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCurriculumLayout.createSequentialGroup()
                        .addComponent(formacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(experienciaE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCurriculumLayout.createSequentialGroup()
                        .addComponent(idiomasE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(aficionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCurriculumLayout.createSequentialGroup()
                        .addComponent(otrosE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCurriculumLayout.createSequentialGroup()
                        .addComponent(apellido1CurriculumE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(apellido1Curriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(apellido2CurriculumE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(apellido2Curriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCurriculumLayout.createSequentialGroup()
                        .addComponent(nombreCurriculumE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(nombreCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(correoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCurriculumLayout.createSequentialGroup()
                        .addComponent(actualizacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(actualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(borrarCurriculum)
                        .addGap(10, 10, 10)
                        .addComponent(aceptarCambiosCurriculum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelCurriculumLayout.setVerticalGroup(
            panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurriculumLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(actualizacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aceptarCambiosCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrarCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCurriculumE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido1CurriculumE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido1Curriculum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2CurriculumE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2Curriculum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(experienciaE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idiomasE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aficionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otrosE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOferta.setPreferredSize(new java.awt.Dimension(940, 520));

        editarOferta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editarOferta.setText("Editar");

        nombreEmpresa.setMaximumSize(new java.awt.Dimension(84, 29));
        nombreEmpresa.setMinimumSize(new java.awt.Dimension(84, 29));
        nombreEmpresa.setPreferredSize(new java.awt.Dimension(84, 29));

        nombreEmpresaE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreEmpresaE.setText("Nombre");

        puestoE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        puestoE.setText("Puesto");

        puesto.setMaximumSize(new java.awt.Dimension(84, 29));
        puesto.setMinimumSize(new java.awt.Dimension(84, 29));
        puesto.setPreferredSize(new java.awt.Dimension(84, 29));

        ubicacionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ubicacionE.setText("Ubicacion");

        ubicacion.setMaximumSize(new java.awt.Dimension(84, 29));
        ubicacion.setMinimumSize(new java.awt.Dimension(84, 29));
        ubicacion.setPreferredSize(new java.awt.Dimension(84, 29));

        requisitos.setColumns(20);
        requisitos.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        requisitos.setLineWrap(true);
        requisitos.setRows(5);
        jScrollPane7.setViewportView(requisitos);

        requisitosE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        requisitosE.setText("Requisitos");

        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        jScrollPane9.setViewportView(descripcion);

        descripcionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        descripcionE.setText("Descripcion");

        salarioE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salarioE.setText("Salario");

        inscritosE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        inscritosE.setText("Inscritos");

        salario.setMaximumSize(new java.awt.Dimension(84, 29));
        salario.setMinimumSize(new java.awt.Dimension(84, 29));
        salario.setPreferredSize(new java.awt.Dimension(84, 29));

        inscritos.setMaximumSize(new java.awt.Dimension(84, 29));
        inscritos.setMinimumSize(new java.awt.Dimension(84, 29));
        inscritos.setPreferredSize(new java.awt.Dimension(84, 29));

        jornadaE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jornadaE.setText("Jornada");

        vacacionesE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        vacacionesE.setText("Dias de vacaciones");

        jornada.setMaximumSize(new java.awt.Dimension(84, 29));
        jornada.setMinimumSize(new java.awt.Dimension(84, 29));
        jornada.setPreferredSize(new java.awt.Dimension(84, 29));

        vacaciones.setMaximumSize(new java.awt.Dimension(84, 29));
        vacaciones.setMinimumSize(new java.awt.Dimension(84, 29));
        vacaciones.setPreferredSize(new java.awt.Dimension(84, 29));

        vacantesE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vacantesE.setText("Vacantes");

        creacionE.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        creacionE.setText("Fecha de creacion");

        vacantes.setMaximumSize(new java.awt.Dimension(84, 29));
        vacantes.setMinimumSize(new java.awt.Dimension(84, 29));
        vacantes.setPreferredSize(new java.awt.Dimension(84, 29));

        creacion.setMaximumSize(new java.awt.Dimension(84, 29));
        creacion.setMinimumSize(new java.awt.Dimension(84, 29));
        creacion.setPreferredSize(new java.awt.Dimension(84, 29));

        aceptarCambiosOferta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aceptarCambiosOferta.setText("Aceptar");

        borrarOferta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        borrarOferta.setText("Borrar");

        javax.swing.GroupLayout panelOfertaLayout = new javax.swing.GroupLayout(panelOferta);
        panelOferta.setLayout(panelOfertaLayout);
        panelOfertaLayout.setHorizontalGroup(
            panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOfertaLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOfertaLayout.createSequentialGroup()
                                .addComponent(puestoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ubicacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOfertaLayout.createSequentialGroup()
                                .addComponent(descripcionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(requisitosE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelOfertaLayout.createSequentialGroup()
                            .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelOfertaLayout.createSequentialGroup()
                                    .addComponent(salarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelOfertaLayout.createSequentialGroup()
                                    .addComponent(inscritosE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(inscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelOfertaLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(vacacionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(vacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(creacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(creacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelOfertaLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jornadaE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(jornada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(vacantesE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(vacantes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelOfertaLayout.createSequentialGroup()
                        .addComponent(nombreEmpresaE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(borrarOferta)
                        .addGap(10, 10, 10)
                        .addComponent(aceptarCambiosOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarOferta)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelOfertaLayout.setVerticalGroup(
            panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(editarOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombreEmpresaE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aceptarCambiosOferta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubicacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requisitosE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jornadaE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacantesE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vacacionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscritosE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        panelUsuario.setPreferredSize(new java.awt.Dimension(940, 520));

        editarUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editarUsuario.setText("Editar");

        nombreUser.setBorder(null);
        nombreUser.setMaximumSize(new java.awt.Dimension(84, 29));
        nombreUser.setMinimumSize(new java.awt.Dimension(84, 29));
        nombreUser.setPreferredSize(new java.awt.Dimension(84, 29));

        nombreUserE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreUserE.setText("Nombre");

        usuarioI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarioI1.setMaximumSize(new java.awt.Dimension(59, 48));
        usuarioI1.setMinimumSize(new java.awt.Dimension(59, 48));
        usuarioI1.setPreferredSize(new java.awt.Dimension(59, 48));

        apellido1UsuarioE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apellido1UsuarioE.setText("Primer apellido");

        apellido1Usuario.setMaximumSize(new java.awt.Dimension(84, 29));
        apellido1Usuario.setMinimumSize(new java.awt.Dimension(84, 29));
        apellido1Usuario.setPreferredSize(new java.awt.Dimension(84, 29));

        apellido2UsuarioE.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        apellido2UsuarioE.setText("Segundo apellido");

        apellido2Usuario.setMaximumSize(new java.awt.Dimension(84, 29));
        apellido2Usuario.setMinimumSize(new java.awt.Dimension(84, 29));
        apellido2Usuario.setPreferredSize(new java.awt.Dimension(84, 29));

        telefono.setMaximumSize(new java.awt.Dimension(84, 29));
        telefono.setMinimumSize(new java.awt.Dimension(84, 29));
        telefono.setPreferredSize(new java.awt.Dimension(84, 29));

        telefonoE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        telefonoE.setText("Telefono");

        correo1.setMaximumSize(new java.awt.Dimension(84, 29));
        correo1.setMinimumSize(new java.awt.Dimension(84, 29));
        correo1.setPreferredSize(new java.awt.Dimension(84, 29));

        correoE1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        correoE1.setText("Correo");

        direccionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        direccionE.setText("Dirección");

        direccion.setMaximumSize(new java.awt.Dimension(84, 29));
        direccion.setMinimumSize(new java.awt.Dimension(84, 29));
        direccion.setPreferredSize(new java.awt.Dimension(84, 29));

        ciudadE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ciudadE.setText("Ciudad");

        ciudad.setMaximumSize(new java.awt.Dimension(84, 29));
        ciudad.setMinimumSize(new java.awt.Dimension(84, 29));
        ciudad.setPreferredSize(new java.awt.Dimension(84, 29));

        nacionalidad.setMaximumSize(new java.awt.Dimension(84, 29));
        nacionalidad.setMinimumSize(new java.awt.Dimension(84, 29));
        nacionalidad.setPreferredSize(new java.awt.Dimension(84, 29));

        nacionalidadE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nacionalidadE.setText("Nacionalidad");

        nacimiento.setMaximumSize(new java.awt.Dimension(84, 29));
        nacimiento.setMinimumSize(new java.awt.Dimension(84, 29));
        nacimiento.setPreferredSize(new java.awt.Dimension(84, 29));

        nacimientoE.setText("Fecha de nacimiento");

        conducir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        conducir.setText("Permiso de conducir");

        contacto.setColumns(20);
        contacto.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        contacto.setLineWrap(true);
        contacto.setRows(5);
        jScrollPane10.setViewportView(contacto);

        contactoE.setText("Persona de contacto");

        informacion.setColumns(20);
        informacion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        informacion.setLineWrap(true);
        informacion.setRows(5);
        jScrollPane11.setViewportView(informacion);

        informacionE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        informacionE.setText("Informacion");

        urlE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        urlE.setText("URL");

        url.setMaximumSize(new java.awt.Dimension(84, 29));
        url.setMinimumSize(new java.awt.Dimension(84, 29));
        url.setPreferredSize(new java.awt.Dimension(84, 29));

        aceptarCambios.setText("Aceptar");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(conducir)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(nacimientoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(nacionalidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(apellido1UsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(apellido1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(correoE1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(ciudadE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(apellido2UsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(apellido2Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(telefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(informacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(urlE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuarioLayout.createSequentialGroup()
                                .addComponent(contactoE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(usuarioI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nombreUserE)
                        .addGap(10, 10, 10)
                        .addComponent(nombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251)
                        .addComponent(aceptarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarUsuario)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(aceptarCambios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreUserE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido1UsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2UsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correoE1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ciudadE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacionalidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimientoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conducir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(urlE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ofertasScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaPrincipalLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(panelCurriculum, 933, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaPrincipalLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(panelOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
            .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaPrincipalLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ofertasScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCurriculum, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)))
            .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelOferta, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)))
            .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hamburguerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE))
            .addComponent(barraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hamburguerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="collapsed" desc="Variables creadas por la vista de diseño">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarCambios;
    private javax.swing.JButton aceptarCambiosCurriculum;
    private javax.swing.JButton aceptarCambiosOferta;
    private javax.swing.JTextField actualizacion;
    private javax.swing.JLabel actualizacionE;
    private javax.swing.JTextArea aficiones;
    private javax.swing.JLabel aficionesE;
    private javax.swing.JTextField apellido1Curriculum;
    private javax.swing.JLabel apellido1CurriculumE;
    private javax.swing.JTextField apellido1Usuario;
    private javax.swing.JLabel apellido1UsuarioE;
    private javax.swing.JTextField apellido2Curriculum;
    private javax.swing.JLabel apellido2CurriculumE;
    private javax.swing.JTextField apellido2Usuario;
    private javax.swing.JLabel apellido2UsuarioE;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JButton borrarCurriculum;
    private javax.swing.JButton borrarOferta;
    private javax.swing.JTextField busqueda;
    private javax.swing.JLabel busquedaI;
    private javax.swing.JTextField ciudad;
    private javax.swing.JLabel ciudadE;
    private javax.swing.JCheckBox conducir;
    private javax.swing.JTextArea contacto;
    private javax.swing.JLabel contactoE;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField correo1;
    private javax.swing.JLabel correoE;
    private javax.swing.JLabel correoE1;
    private javax.swing.JTextField creacion;
    private javax.swing.JLabel creacionE;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel descripcionE;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionE;
    private javax.swing.JButton editar;
    private javax.swing.JButton editarOferta;
    private javax.swing.JButton editarUsuario;
    private javax.swing.JLabel etiquetaVacia;
    private javax.swing.JTextArea experiencia;
    private javax.swing.JLabel experienciaE;
    private javax.swing.JTextArea formacion;
    private javax.swing.JLabel formacionE;
    private javax.swing.JPanel hamburguerMenu;
    private javax.swing.JTextArea idiomas;
    private javax.swing.JLabel idiomasE;
    private javax.swing.JTextArea informacion;
    private javax.swing.JLabel informacionE;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JTextField inscritos;
    private javax.swing.JLabel inscritosE;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jornada;
    private javax.swing.JLabel jornadaE;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField nacimiento;
    private javax.swing.JLabel nacimientoE;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JLabel nacionalidadE;
    private javax.swing.JTextField nombreCurriculum;
    private javax.swing.JLabel nombreCurriculumE;
    private javax.swing.JTextField nombreEmpresa;
    private javax.swing.JLabel nombreEmpresaE;
    private javax.swing.JTextField nombreUser;
    private javax.swing.JLabel nombreUserE;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JScrollPane ofertasScroll;
    private javax.swing.JList<String> opciones;
    private javax.swing.JTextArea otros;
    private javax.swing.JLabel otrosE;
    private javax.swing.JPanel panelCurriculum;
    private javax.swing.JPanel panelInvisible;
    private javax.swing.JPanel panelOferta;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JTextField puesto;
    private javax.swing.JLabel puestoE;
    private javax.swing.JButton registrarse;
    private javax.swing.JTextArea requisitos;
    private javax.swing.JLabel requisitosE;
    private javax.swing.JTextField salario;
    private javax.swing.JLabel salarioE;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoE;
    private javax.swing.JTextField ubicacion;
    private javax.swing.JLabel ubicacionE;
    private javax.swing.JTextField url;
    private javax.swing.JLabel urlE;
    private javax.swing.JLabel usuarioI;
    private javax.swing.JLabel usuarioI1;
    private javax.swing.JTextField vacaciones;
    private javax.swing.JLabel vacacionesE;
    private javax.swing.JTextField vacantes;
    private javax.swing.JLabel vacantesE;
    private javax.swing.JPanel ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
    
    /**
     * Método que cierra la venatan hija que se le pase por parametro.
     * @param hijo Ventana hija de la aplicación principal.
     */
    public void cerrarHijo(JFrame hijo)
    {
        if(hijo.equals(inicioSesion))
            inicioSesion = null;
        else if(hijo.equals(registrar))
            registrar = null;
        else if(hijo.equals(configuracion))
            configuracion = null;
        else if(hijo.equals(curriculum))
            curriculum = null;
        else if(hijo.equals(oferta))
            oferta = null;
        hijo.dispose();
    }
    
    //<editor-fold defaultstate="collapsed" desc="Getter y Setter">
    /**
     * Obtiene el usuario de la aplicación.
     * @return Usuario con los datos de la persona que ha iniciado sesión.
     */
    public Usuario getUsuario()
    {
        return usuario;
    }

    /**
     * Da a la variable Usuario de la aplicación un valor.
     * @param usuario Usuario a guardar dentro de la aplicación.
     */
    public void setUsuario(Usuario usuario)
    {
        this.usuario = usuario;
    }
    
    /**
     * Obtiene la lista de opciones a mostrar en el menú desplegable de la aplicación.
     * @return Lista con las opciones del menú lateral.
     */
    public JList<String> getOpciones()
    {
        return opciones;
    }
    
    /**
     * Obtiene la etiqueta que contiene la imagen del menú hamburguesa o la X.
     * @return JLabel con un Icon.
     */
    public JLabel getMenu()
    {
        return menu;
    }
    
    /**
     * Cambia el valor de la variable booleana Menu Abierta.
     * @param valor True o False en función del valor que se quiera dar al Menú Abierto, dependientdo del estado anterior del menú.
     */
    public void setMenuAbierto(boolean valor)
    {
        menuAbierto = valor;
    }
    
    /**
     * Obtiene la variable booleana Menú Abierto.
     * @return Yrue si está el menú abierto y False si está cerrado.
     */
    public boolean getMenuAbierto()
    {
        return menuAbierto;
    }
    
    /**
     * Panel que contiene los elementos de la barra superior de la Ventana Principal.
     * @return JPanel con 3 iconos, dos botones y una barra de búsqueda.
     */
    public JPanel getBarraSuperior()
    {
        return barraSuperior;
    }
    
    public JPanel getHamburguerMenu()
    {
        return hamburguerMenu;
    }
    
    public JLabel getNombreUsuario()
    {
        return nombreUsuario;
    }

    public CrearUsuario getRegistrar()
    {
        return registrar;
    }

    public JButton getRegistrarse()
    {
        return registrarse;
    }

    public JLabel getUsuarioI()
    {
        return usuarioI;
    }

    public JPanel getVentanaPrincipal()
    {
        return ventanaPrincipal;
    }
    
    public JButton getIniciarSesion()
    {
        return iniciarSesion;
    }

    public Loging getInicioSesion()
    {
        return inicioSesion;
    }

    public Configuracion getConfiguracion()
    {
        return configuracion;
    }

    public JTextField getBusqueda()
    {
        return busqueda;
    }

    public JLabel getBusquedaI()
    {
        return busquedaI;
    }

    public JPanel getOfertas()
    {
        return panelInvisible;
    }

    public JScrollPane getOfertasScroll()
    {
        return ofertasScroll;
    }

    public boolean isMenuAbierto()
    {
        return menuAbierto;
    }

    public void setInicioSesion(Loging inicioSesion)
    {
        this.inicioSesion = inicioSesion;
    }

    public void setRegistrar(CrearUsuario registrar)
    {
        this.registrar = registrar;
    }
    
    public static Color getColorDefecto()
    {
        return colorDefecto;
    }

    public static void setColorDefecto(Color colorDefecto)
    {
        VentanaPrincipal.colorDefecto = colorDefecto;
    }

    public static Color getColorTextoDefecto()
    {
        return colorTextoDefecto;
    }

    public static void setColorTextoDefecto(Color colorTextoDefecto)
    {
        VentanaPrincipal.colorTextoDefecto = colorTextoDefecto;
    }

    public static Color getColorJTextFieldDefecto()
    {
        return colorJTextFieldDefecto;
    }

    public static void setColorJTextFieldDefecto(Color colorJTextFieldDefecto)
    {
        VentanaPrincipal.colorJTextFieldDefecto = colorJTextFieldDefecto;
    }

    public static Color getColorJTextFieldTextoDefecto()
    {
        return colorJTextFieldTextoDefecto;
    }

    public static void setColorJTextFieldTextoDefecto(Color colorJTextFieldTextoDefecto)
    {
        VentanaPrincipal.colorJTextFieldTextoDefecto = colorJTextFieldTextoDefecto;
    }

    public CrearCurriculum getCurriculum()
    {
        return curriculum;
    }

    public void setCurriculum(CrearCurriculum curriculum)
    {
        this.curriculum = curriculum;
    }

    public void setConfiguracion(Configuracion configuracion)
    {
        this.configuracion = configuracion;
    }

    public Ofertas getOferta()
    {
        return oferta;
    }

    public void setOferta(Ofertas oferta)
    {
        this.oferta = oferta;
    }
    
    public JPanel getPanelInvisible()
    {
        return panelInvisible;
    }
    
    public boolean isBotonActivado()
    {
        return botonActivado;
    }

    public void setBotonActivado(boolean botonActivado)
    {
        this.botonActivado = botonActivado;
    }

    public boolean isTextoActivado()
    {
        return textoActivado;
    }

    public void setTextoActivado(boolean textoActivado)
    {
        this.textoActivado = textoActivado;
    }
    
    public JTextField getActualizacion()
    {
        return actualizacion;
    }

    public JLabel getActualizacionE()
    {
        return actualizacionE;
    }

    public JTextArea getAficiones()
    {
        return aficiones;
    }

    public JLabel getAficionesE()
    {
        return aficionesE;
    }

    public JTextField getApellido1Curriculum()
    {
        return apellido1Curriculum;
    }

    public JLabel getApellido1E()
    {
        return apellido1CurriculumE;
    }

    public JLabel getApellido1E1()
    {
        return apellido1UsuarioE;
    }

    public JTextField getApellido2Curriculum()
    {
        return apellido2Curriculum;
    }

    public JLabel getApellido2E()
    {
        return apellido2CurriculumE;
    }

    public JLabel getApellido2E1()
    {
        return apellido2UsuarioE;
    }

    public JTextField getApellido3()
    {
        return apellido1Usuario;
    }

    public JTextField getApellido4()
    {
        return apellido2Usuario;
    }

    public JTextField getCiudad()
    {
        return ciudad;
    }

    public JLabel getCiudadE()
    {
        return ciudadE;
    }

    public JCheckBox getConducir()
    {
        return conducir;
    }

    public JTextArea getContacto()
    {
        return contacto;
    }

    public JLabel getContactoE()
    {
        return contactoE;
    }

    public JTextField getCorreo()
    {
        return correo;
    }

    public JTextField getCorreo1()
    {
        return correo1;
    }

    public JLabel getCorreoE()
    {
        return correoE;
    }

    public JLabel getCorreoE1()
    {
        return correoE1;
    }

    public JTextField getCreacion()
    {
        return creacion;
    }

    public JLabel getCreacionE()
    {
        return creacionE;
    }

    public JTextArea getDescripcion()
    {
        return descripcion;
    }

    public JLabel getDescripcionE()
    {
        return descripcionE;
    }

    public JTextField getDireccion()
    {
        return direccion;
    }

    public JLabel getDireccionE()
    {
        return direccionE;
    }

    public JButton getEditar()
    {
        return editar;
    }

    public JLabel getEtiquetaVacia()
    {
        return etiquetaVacia;
    }

    public JTextArea getExperiencia()
    {
        return experiencia;
    }

    public JLabel getExperienciaE()
    {
        return experienciaE;
    }

    public JTextArea getFormacion()
    {
        return formacion;
    }

    public JLabel getFormacionE()
    {
        return formacionE;
    }

    public JTextArea getIdiomas()
    {
        return idiomas;
    }

    public JLabel getIdiomasE()
    {
        return idiomasE;
    }

    public JTextArea getInformacion()
    {
        return informacion;
    }

    public JLabel getInformacionE()
    {
        return informacionE;
    }

    public JTextField getInscritos()
    {
        return inscritos;
    }

    public JLabel getInscritosE()
    {
        return inscritosE;
    }

    public JScrollPane getjScrollPane10()
    {
        return jScrollPane10;
    }

    public JScrollPane getjScrollPane11()
    {
        return jScrollPane11;
    }

    public JScrollPane getjScrollPane3()
    {
        return jScrollPane3;
    }

    public JScrollPane getjScrollPane4()
    {
        return jScrollPane4;
    }

    public JScrollPane getjScrollPane5()
    {
        return jScrollPane5;
    }

    public JScrollPane getjScrollPane6()
    {
        return jScrollPane6;
    }

    public JScrollPane getjScrollPane7()
    {
        return jScrollPane7;
    }

    public JScrollPane getjScrollPane8()
    {
        return jScrollPane8;
    }

    public JScrollPane getjScrollPane9()
    {
        return jScrollPane9;
    }

    public JTextField getJornada()
    {
        return jornada;
    }

    public JLabel getJornadaE()
    {
        return jornadaE;
    }

    public JTextField getNacimiento()
    {
        return nacimiento;
    }

    public JLabel getNacimientoE()
    {
        return nacimientoE;
    }

    public JTextField getNacionalidad()
    {
        return nacionalidad;
    }

    public JLabel getNacionalidadE()
    {
        return nacionalidadE;
    }

    public JTextField getNombreCurriculum()
    {
        return nombreCurriculum;
    }

    public JTextField getNombreEmpresa()
    {
        return nombreEmpresa;
    }

    public JTextField getNombreUser()
    {
        return nombreUser;
    }

    public JLabel getNombreE()
    {
        return nombreCurriculumE;
    }

    public JLabel getNombreEmpresaE()
    {
        return nombreEmpresaE;
    }

    public JLabel getNombreUserE()
    {
        return nombreUserE;
    }

    public JTextArea getOtros()
    {
        return otros;
    }

    public JLabel getOtrosE()
    {
        return otrosE;
    }

    public JPanel getPanelCurriculum()
    {
        return panelCurriculum;
    }

    public JPanel getPanelOferta()
    {
        return panelOferta;
    }

    public JPanel getPanelUsuario()
    {
        return panelUsuario;
    }

    public JTextField getPuesto()
    {
        return puesto;
    }

    public JLabel getPuestoE()
    {
        return puestoE;
    }

    public JTextArea getRequisitos()
    {
        return requisitos;
    }

    public JLabel getRequisitosE()
    {
        return requisitosE;
    }

    public JTextField getSalario()
    {
        return salario;
    }

    public JLabel getSalarioE()
    {
        return salarioE;
    }

    public JTextField getTelefono()
    {
        return telefono;
    }

    public JLabel getTelefonoE()
    {
        return telefonoE;
    }

    public JTextField getUbicacion()
    {
        return ubicacion;
    }

    public JLabel getUbicacionE()
    {
        return ubicacionE;
    }

    public JTextField getUrl()
    {
        return url;
    }

    public JLabel getUrlE()
    {
        return urlE;
    }

    public JLabel getUsuarioI1()
    {
        return usuarioI1;
    }

    public JTextField getVacaciones()
    {
        return vacaciones;
    }

    public JLabel getVacacionesE()
    {
        return vacacionesE;
    }

    public JTextField getVacantes()
    {
        return vacantes;
    }

    public JLabel getVacantesE()
    {
        return vacantesE;
    }
    
    public JButton getEditarOferta()
    {
        return editarOferta;
    }

    public ArrayList<Component> getArr()
    {
        return arr;
    }
    
    public ArrayList<Object> getResultados()
    {
        return resultados;
    }

    public JButton getEditarUsuario()
    {
        return editarUsuario;
    }
    
    public JButton getAceptarCambiosUsuario()
    {
        return aceptarCambios;
    }
    
    public JButton getAceptarCambiosCurriculum()
    {
        return aceptarCambiosCurriculum;
    }
    
    public JButton getAceptarCambiosOferta()
    {
        return aceptarCambiosOferta;
    }
    
    /**
     * Obtiene el valor de la variable Mostrar Curriculum.
     * @return True si muestra un curriculum y False si no lo está mostrando.
     */
    public boolean getMostrarCurriculum()
    {
        return mostrarCurriculum;
    }
    
    /**
     * Cambia el valor de la variable booleana con la que se indica si se está mostrando un curriculum o no.
     * @param mC True o False en función del valor anterior.
     */
    public void setMostrarCurriculum(boolean mC)
    {
        mostrarCurriculum = mC;
    }

    public JButton getAceptarCambios()
    {
        return aceptarCambios;
    }

    public JButton getBorrarCurriculum()
    {
        return borrarCurriculum;
    }

    public JButton getBorrarOferta()
    {
        return borrarOferta;
    }
    //</editor-fold>
}
